### ISSUE TITLE
'lua52.dll' not found

### ISSUE THREAD

**Issue by samwfowler** [umby24/Hypercube#4]
Hey, wanted to try out your software, but when I attempted to start it, I get this error: "Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'lua52': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

I do have lua52.dll in my server folder, haven't moved it at all, hope this helps :)

**Comment by umby24** [comment]
Are you running on linux/mono?

**Comment by samwfowler** [comment]
Naa, running windows :)

**Comment by umby24** [comment]
Hm well that's different :p so you have servercli.exe, hypercube.dll, nlua.dll, and lua52.dll all in the same folder?
